services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-2727}:2727"
    volumes:
      - ./config.json:/app/config.json
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_USER=${POSTGRES_USER:-user}
      - DATABASE_NAME=kalmia
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD:-password}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: kalmia
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d kalmia"]
      interval: 10s
      timeout: 10s
      retries: 10
