name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: |
        go mod download
        cd web && pnpm install
        cd ..

    - name: Build web
      run: cd web && npx rsbuild build && cd ..

    - name: Build for all platforms
      run: make build

    - name: Upload release assets
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
            dist/kalmia_${{ github.ref_name }}_freebsd_amd64
            dist/kalmia_${{ github.ref_name }}_freebsd_arm64
            dist/kalmia_${{ github.ref_name }}_linux_386
            dist/kalmia_${{ github.ref_name }}_linux_amd64
            dist/kalmia_${{ github.ref_name }}_linux_arm
            dist/kalmia_${{ github.ref_name }}_linux_arm64
            dist/kalmia_${{ github.ref_name }}_linux_riscv64
            dist/kalmia_${{ github.ref_name }}_macos_amd64
            dist/kalmia_${{ github.ref_name }}_macos_arm64
            dist/kalmia_${{ github.ref_name }}_windows_386.exe
            dist/kalmia_${{ github.ref_name }}_windows_amd64.exe
            dist/kalmia_${{ github.ref_name }}_windows_arm64.exe

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Cleanup build artifacts
      run: make clean
